"""Security package for Prompt Injection & Adversarial Defense."""
from app.agent.security.injection_guard import (
    normalize_text_for_security,
    normalize_leetspeak,
    scan_prompt_injection,
    scan_encoded_payloads,
    validate_untrusted_input,
    sanitize_untrusted_input,
    sanitize_interview_answer,
    sanitize_extracted_field,
    InjectionScanResult,
    SECURITY_FLAGS,
    MAX_ANSWER_CHARS,
    MAX_PROBE_CHARS,
    FLAG_INJECTION_DETECTED,
    FLAG_OBFUSCATED_BASE64,
    FLAG_OBFUSCATED_HEX,
    FLAG_OBFUSCATED_BINARY,
    FLAG_OBFUSCATED_ROT13,
    FLAG_OBFUSCATED_UNICODE,
    FLAG_OBFUSCATED_LEETSPEAK,
    FLAG_COMMENT_SMUGGLING,
    FLAG_SPECIAL_TOKENS,
    FLAG_SCORING_COERCION,
    FLAG_MULTI_LINGUAL_INJECTION,
    FLAG_DELIMITER_TAMPERING,
)
from app.agent.security.delimiters import (
    wrap_untrusted_content,
    build_secure_llm_payload,
    generate_secure_nonce,
)

__all__ = [
    "normalize_text_for_security",
    "normalize_leetspeak",
    "scan_prompt_injection",
    "scan_encoded_payloads",
    "validate_untrusted_input",
    "sanitize_untrusted_input",
    "sanitize_interview_answer",
    "sanitize_extracted_field",
    "InjectionScanResult",
    "SECURITY_FLAGS",
    "MAX_ANSWER_CHARS",
    "MAX_PROBE_CHARS",
    "FLAG_INJECTION_DETECTED",
    "FLAG_OBFUSCATED_BASE64",
    "FLAG_OBFUSCATED_HEX",
    "FLAG_OBFUSCATED_BINARY",
    "FLAG_OBFUSCATED_ROT13",
    "FLAG_OBFUSCATED_UNICODE",
    "FLAG_OBFUSCATED_LEETSPEAK",
    "FLAG_COMMENT_SMUGGLING",
    "FLAG_SPECIAL_TOKENS",
    "FLAG_SCORING_COERCION",
    "FLAG_MULTI_LINGUAL_INJECTION",
    "FLAG_DELIMITER_TAMPERING",
    "wrap_untrusted_content",
    "build_secure_llm_payload",
    "generate_secure_nonce",
]

