import { Campaign, Candidate, CandidateStage } from "./types";

export const CAMPAIGNS: Campaign[] = [
  { id: "c1", title: "Senior Frontend Engineer", department: "Engineering", location: "Remote · London", status: "active", total: 42, processed: 38, shortlisted: 6, created: "12 Jun 2025" },
  { id: "c2", title: "Product Manager", department: "Product", location: "New York, NY", status: "active", total: 28, processed: 24, shortlisted: 5, created: "8 Jun 2025" },
  { id: "c3", title: "DevOps Lead", department: "Infrastructure", location: "Berlin · Remote", status: "completed", total: 31, processed: 31, shortlisted: 3, created: "1 Jun 2025" },
  { id: "c4", title: "Data Scientist", department: "Analytics", location: "San Francisco, CA", status: "paused", total: 15, processed: 8, shortlisted: 2, created: "28 May 2025" },
];

export const CANDIDATES: Candidate[] = [
  { id: "cand1", campaignId: "c1", name: "Aria Chen", email: "aria.chen@gmail.com", currentRole: "Frontend Lead at Monzo", experience: "7 years", score: 91, stage: "shortlisted", recommendation: "shortlist", scores: { technical: 94, communication: 88, culturalFit: 90, problemSolving: 92, leadership: 85, domain: 95 }, summary: "Aria brings exceptional depth in React ecosystem architecture and has led frontend teams at scale. Her design-system ownership and performance optimisation at Monzo are exemplary. Communication is clear, structured, and collaborative.", strengths: ["Led design system used by 40+ engineers", "Core Web Vitals expertise (98 Lighthouse)", "Strong TypeScript & testing philosophy", "Proven cross-functional collaboration"], concerns: ["Limited GraphQL at scale", "Primarily B2C background"], transcript: [{ role: "ai", message: "Hi Aria. Walk me through the biggest technical challenge you owned at Monzo.", time: "09:02" }, { role: "candidate", message: "Rebuilding our design system from scratch. Led a team of three, went from zero to a fully token-based system in six months.", time: "09:03" }, { role: "ai", message: "How did you handle adoption across teams mid-sprint?", time: "09:04" }, { role: "candidate", message: "Dual-track approach — maintained the old system while building the new one, with fortnightly workshops. Adoption hit 80% in three months because teams felt ownership, not mandate.", time: "09:05" }, { role: "ai", message: "Describe your approach to diagnosing a slow React render.", time: "09:06" }, { role: "candidate", message: "React DevTools Profiler first. Then I look at data flow — usually missing memoisation, unstable prop references, or expensive computations in the render path. Fix in isolation and measure before and after.", time: "09:07" }, { role: "ai", message: "What attracts you to this specific role?", time: "09:09" }, { role: "candidate", message: "The scale and architectural ambition. Real ownership on offer — that's the environment where I do my best work.", time: "09:10" }] },
  { id: "cand2", campaignId: "c1", name: "Marcus Webb", email: "m.webb@outlook.com", currentRole: "Senior Engineer at Deliveroo", experience: "5 years", score: 84, stage: "shortlisted", recommendation: "shortlist", scores: { technical: 86, communication: 82, culturalFit: 85, problemSolving: 80, leadership: 78, domain: 88 }, summary: "Marcus shows solid React and Node expertise with a product-minded approach. High-traffic system experience is directly relevant.", strengths: ["Full-stack proficiency", "High-traffic system experience", "Clear architectural thinking"], concerns: ["Less team leadership experience", "Occasionally vague on specifics"], transcript: [{ role: "ai", message: "Walk me through the most complex system you've built.", time: "10:01" }, { role: "candidate", message: "The order tracking pipeline at Deliveroo — real-time, thousands of concurrent orders, sub-second UI updates.", time: "10:02" }] },
  { id: "cand3", campaignId: "c1", name: "Priya Sharma", email: "priya.sharma@proton.me", currentRole: "Frontend Engineer at Razorpay", experience: "4 years", score: 78, stage: "interviewing", recommendation: "pending", scores: { technical: 80, communication: 75, culturalFit: 82, problemSolving: 76, leadership: 65, domain: 79 }, summary: "Priya demonstrates solid fundamentals and genuine interest in performance engineering. Early in her leadership journey but technically capable.", strengths: ["Strong CSS & animation skills", "Passionate about accessibility"], concerns: ["No significant team leadership", "Limited large codebase exposure"], transcript: [] },
  { id: "cand4", campaignId: "c1", name: "Jordan Blake", email: "jordan.blake@yahoo.com", currentRole: "Mid-level Developer at AgencyX", experience: "3 years", score: 65, stage: "screening", recommendation: "pending", scores: { technical: 62, communication: 70, culturalFit: 68, problemSolving: 60, leadership: 55, domain: 65 }, summary: "Jordan shows promise but current skill level is below the senior threshold.", strengths: ["Eager to learn", "Good communication"], concerns: ["JD match below 70%", "Limited production experience"], transcript: [] },
  { id: "cand5", campaignId: "c1", name: "Sam Torres", email: "sam.t@gmail.com", currentRole: "Junior Dev at StartupCo", experience: "1.5 years", score: 38, stage: "rejected", recommendation: "reject", scores: { technical: 35, communication: 50, culturalFit: 45, problemSolving: 38, leadership: 30, domain: 36 }, summary: "Sam's experience does not meet the minimum requirements for a senior role.", strengths: ["Enthusiasm for the role"], concerns: ["Significantly under-qualified", "No React production experience"], transcript: [] },
  { id: "cand6", campaignId: "c1", name: "Nina Kowalski", email: "nina.k@tech.pl", currentRole: "Principal Engineer at Allegro", experience: "9 years", score: 88, stage: "shortlisted", recommendation: "shortlist", scores: { technical: 90, communication: 85, culturalFit: 87, problemSolving: 89, leadership: 92, domain: 86 }, summary: "Nina has exceptional breadth and depth. Her Principal Engineer background means she operates well above the role requirements.", strengths: ["Principal-level system design", "Strong mentorship background", "Excellent problem decomposition"], concerns: ["May be overqualified — retention risk", "Salary expectations at ceiling"], transcript: [] },
  { id: "cand7", campaignId: "c1", name: "Luca Ferretti", email: "luca.ferretti@icloud.com", currentRole: "Frontend Architect at Klarna", experience: "6 years", score: 82, stage: "pending", recommendation: "pending", scores: { technical: 84, communication: 80, culturalFit: 79, problemSolving: 81, leadership: 74, domain: 85 }, summary: "Luca is pending initial screening. Strong CV with fintech background.", strengths: ["Fintech domain expertise", "Strong system design portfolio"], concerns: ["Screening not yet complete"], transcript: [] },
];

export const STAGE_CONFIG: Record<CandidateStage, { label: string; color: string }> = {
  pending:      { label: "Pending Screening", color: "#808090" },
  screening:    { label: "Screening",         color: "#C09040" },
  rejected:     { label: "Rejected",          color: "#C04040" },
  interviewing: { label: "Interviewing",      color: "#4088C0" },
  shortlisted:  { label: "AI Shortlisted",    color: "#40A060" },
};
